version: '3'

networks:
  stuvio:
    driver: bridge

services:
  python:
    build: ./python/.
    container_name: stuvio-server-python
    volumes:
      - ./python/server:/server
    ports: 
      - 5000:5000
    networks: 
      - stuvio
  
  
  